#!/bin/bash

#Define the file and pattern
FILE="/home/schipmunk/.config/niri/config.kdl"

if grep -q "//off //monitor off" "$FILE"; then
    sed -i 's/\/\/off \/\/monitor off/off \/\/monitor off/' "$FILE"
    notify-send "Output Changed" "TV is Off"
else
    sed -i 's/off \/\/monitor off/\/\/off \/\/monitor off/' "$FILE"
    notify-send "Output Changed" "TV is On"
fi
