#!/bin/bash

#Define the file and pattern
FILE="$HOME/.config/niri/includes/output.kdl"

if grep -q "//off //toggletv" "$FILE"; then
    sed -i 's/\/\/off \/\/toggletv/off \/\/toggletv/' "$FILE"
    notify-send "Output Changed" "TV is Off"
else
    sed -i 's/off \/\/toggletv/\/\/off \/\/toggletv/' "$FILE"
    notify-send "Output Changed" "TV is On"
fi
